# Generated by Django 4.2.7 on 2023-11-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_category_item_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='1'),
            preserve_default=False,
        ),
    ]
